-- Words テーブル
CREATE TABLE IF NOT EXISTS words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_text VARCHAR(255),
    kana_reading VARCHAR(255),
    romaji_target VARCHAR(255)
);

-- Magic Words テーブル
CREATE TABLE IF NOT EXISTS magic_words (
    magic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    magic_text VARCHAR(255),
    magic_reading VARCHAR(255),
    magic_target VARCHAR(255)
);

-- Single Results テーブル
CREATE TABLE IF NOT EXISTS single_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    score INT,
    accuracy_rate INT,
    finished_at TIMESTAMP
);

-- Battle Results テーブル
CREATE TABLE IF NOT EXISTS battle_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1_id INT,
    player2_id INT,
    winner_id INT,
    player1_score INT,
    player2_score INT,
    player1_accuracy_rate INT,
    player2_accuracy_rate INT,
    finished_at TIMESTAMP
);
