-- Users テーブル
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    icon_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    background_image INT DEFAULT 0
);

-- Words テーブル
CREATE TABLE IF NOT EXISTS words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_text VARCHAR(255),
    kana_reading VARCHAR(255),
    romaji_target VARCHAR(255)
);

-- Magic Words テーブル
CREATE TABLE IF NOT EXISTS magic_words (
    magic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    magic_text VARCHAR(255),
    magic_reading VARCHAR(255),
    magic_target VARCHAR(255)
);

-- Single Results テーブル
CREATE TABLE IF NOT EXISTS single_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    score INT,
    accuracy_rate INT,
    finished_at TIMESTAMP
);

-- Battle Results テーブル
CREATE TABLE IF NOT EXISTS battle_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player1_id BIGINT,
    player2_id BIGINT,
    winner_id BIGINT,
    player1_score INT,
    player2_score INT,
    player1_accuracy_rate INT,
    player2_accuracy_rate INT,
    finished_at TIMESTAMP
);
